import type { LocalizedListItem, LocalizedText, SiteContent, SiteLayouts, SystemBlockItem } from "@/lib/types";

const text = (en: string, ar: string, color?: string): LocalizedText => ({ en, ar, ...(color ? { color } : {}) });
const item = (id: string, en: string, ar: string): LocalizedListItem => ({ id, text: text(en, ar) });
const decisionCard = (
  id: string,
  enLabel: string,
  arLabel: string,
  enTitle: string,
  arTitle: string,
  enCopy: string,
  arCopy: string,
  enCta?: string,
  arCta?: string,
) => ({
  id,
  label: text(enLabel, arLabel),
  title: text(enTitle, arTitle),
  copy: text(enCopy, arCopy),
  ...(enCta && arCta ? { cta: text(enCta, arCta) } : {}),
});
const valueCard = (
  id: string,
  enLabel: string,
  arLabel: string,
  enValue: string,
  arValue: string,
  enNote: string,
  arNote: string,
) => ({
  id,
  label: text(enLabel, arLabel),
  value: text(enValue, arValue),
  note: text(enNote, arNote),
});
const faq = (id: string, enQuestion: string, arQuestion: string, enAnswer: string, arAnswer: string) => ({
  id,
  question: text(enQuestion, arQuestion),
  answer: text(enAnswer, arAnswer),
});

export const defaultSiteLayouts: SiteLayouts = {
  home: [
    { id: "service-architecture", label: text("Service architecture", "هيكل الخدمات"), enabled: true },
    { id: "featured-projects", label: text("Featured projects", "المشروعات المميزة"), enabled: true },
    { id: "calculators", label: text("Calculators", "الحاسبات"), enabled: true },
    { id: "service-modules", label: text("Service modules", "الخدمات المكملة"), enabled: true },
    { id: "lead-capture", label: text("Lead capture", "التقاط الطلبات"), enabled: true },
  ],
  projects: [
    { id: "projects-hero", label: text("Projects hero", "هيدر المشروعات"), enabled: true },
    { id: "projects-grid", label: text("Projects grid", "شبكة المشروعات"), enabled: true },
  ],
  finishing: [
    { id: "finishing-hero", label: text("Finishing hero", "هيدر التشطيب"), enabled: true },
    { id: "finishing-packages", label: text("Packages", "الباقات"), enabled: true },
    { id: "finishing-lead", label: text("Lead block", "قسم الطلب"), enabled: true },
  ],
  smartHome: [
    { id: "smart-hero", label: text("Smart hero", "هيدر المنزل الذكي"), enabled: true },
    { id: "smart-devices", label: text("Devices grid", "شبكة الأجهزة"), enabled: true },
    { id: "smart-packages", label: text("Packages + lead", "الباقات والطلب"), enabled: true },
  ],
  book: [
    { id: "book-hero", label: text("Booking hero", "هيدر الحجز"), enabled: true },
    { id: "book-form", label: text("Booking form", "نموذج الحجز"), enabled: true },
  ],
};

export const defaultSystemBlocks: SystemBlockItem[] = [
  {
    id: "global-nav-shell",
    label: text("Global nav shell", "الهيكل الملاحي العام"),
    zone: "header",
    pages: ["home", "projects", "finishing", "smartHome", "book"],
    enabled: true,
    conditions: { locale: "all", visitorIntent: "all" },
  },
  {
    id: "global-top-cta",
    label: text("Top CTA button", "زر الإجراء العلوي"),
    zone: "header",
    pages: ["home", "projects", "finishing", "smartHome", "book"],
    enabled: true,
    conditions: { locale: "all", visitorIntent: "all" },
  },
  {
    id: "shared-lead-entry",
    label: text("Shared lead form entry", "مدخل نموذج العملاء الموحد"),
    zone: "lead",
    pages: ["home", "projects", "finishing", "smartHome", "book"],
    enabled: true,
    conditions: { locale: "all", visitorIntent: "all" },
  },
  {
    id: "global-footer-shell",
    label: text("Global footer shell", "هيكل الفوتر العام"),
    zone: "footer",
    pages: ["home", "projects", "finishing", "smartHome", "book"],
    enabled: true,
    conditions: { locale: "all", visitorIntent: "all" },
  },
];

export const defaultPageContent: NonNullable<SiteContent["pages"]> = {
  home: {
    serviceArchitectureEyebrow: text("Service architecture", "هيكل الخدمات"),
    serviceArchitectureTitle: text(
      "Three business lines with one luxury operating language.",
      "ثلاثة مسارات أعمال بلغة تشغيل فاخرة وموحدة.",
    ),
    serviceArchitectureDescription: text(
      "Each service behaves like its own premium product while the brand stays coherent.",
      "كل خدمة تتحرك كمنتج فاخر مستقل مع بقاء هوية العلامة واضحة ومتماسكة.",
    ),
    featuredEyebrow: text("Featured projects", "المشروعات المميزة"),
    featuredTitle: text(
      "Present projects like premium showcases, not flat listing blocks.",
      "قدّم المشروعات كعروض فاخرة لا ككروت عرض تقليدية.",
    ),
    featuredDescription: text(
      "Use imagery, metrics, and unit highlights to accelerate decision-making.",
      "استخدم الصورة والمؤشرات والوحدات البارزة لتسريع القرار.",
    ),
    leadEyebrow: text("Lead capture", "التقاط الطلبات"),
    leadTitle: text(
      "Close the journey with one clear conversion block.",
      "اختم الرحلة بنقطة تحويل واحدة وواضحة.",
    ),
    leadDescription: text(
      "The form remains practical, but the context now feels like a premium final step.",
      "النموذج يظل عمليًا لكن السياق المحيط به أصبح أقرب لخطوة ختامية فاخرة.",
    ),
    serviceModulesEyebrow: text("Service modules", "الخدمات المكملة"),
    serviceModulesTitle: text(
      "Finishing and smart-home offers should feel like premium upsells.",
      "التشطيب والمنزل الذكي يجب أن يظهرا كترقيات مدروسة وفاخرة.",
    ),
    serviceModulesDescription: text(
      "Each module keeps its own business logic while extending the real-estate journey.",
      "كل مسار يحتفظ بمنطقه التجاري مع استكمال رحلة العقار الأساسية.",
    ),
    signatureLaunch: text("Signature launch", "الإطلاق الرئيسي"),
    primeInventory: text("Prime inventory", "الوحدات الأبرز"),
    unitTypesLabel: text("unit types", "أنواع وحدات"),
    investmentFlow: text("Mixed-use investment flow", "تدفق استثماري متعدد الاستخدامات"),
    platformMode: text("Platform mode", "وضع المنصة"),
    separateAdmin: text("Separate admin domain ready", "دومين إدارة منفصل جاهز"),
    intentEyebrow: text("Choose the right path first", "اختر المسار الصحيح أولًا"),
    intentTitle: text(
      "Start with intent, then move to the right next step fast.",
      "ابدأ بالنية الصحيحة ثم انتقل إلى الخطوة التالية بسرعة.",
    ),
    intentDescription: text(
      "Route visitors into buying, finishing, or smart-home consultation instead of making them decode the whole platform alone.",
      "وجّه الزائر مباشرة إلى الشراء أو التشطيب أو استشارة المنزل الذكي بدل تركه يفسر المنصة وحده.",
    ),
    trustTitle: text(
      "Why does the journey convert better with Veyra?",
      "ما الذي يجعل الرحلة أكثر وضوحًا وتحويلًا مع Veyra؟",
    ),
    bookingTitle: text("Before you submit", "قبل أن ترسل الطلب"),
    serviceLines: [
      {
        id: "home-line-projects",
        title: text("Projects", "المشروعات"),
        copy: text(
          "Scalable project listings, unit inventories, installment flows, and visit booking.",
          "عرض مشروعات ديناميكي مع وحدات وتقسيط وحجز زيارات.",
        ),
        stat: text("Residential + Mixed-use", "سكني ومتعدد الاستخدامات"),
        link: text("Open section", "افتح القسم"),
      },
      {
        id: "home-line-finishing",
        title: text("Finishing", "التشطيب"),
        copy: text(
          "Package-driven finishing journeys with estimation logic and direct quote requests.",
          "رحلات تشطيب مبنية على الباقات مع منطق تقدير وطلب عرض سعر مباشر.",
        ),
        stat: text("Three pricing tiers", "ثلاث فئات سعرية"),
        link: text("Open section", "افتح القسم"),
      },
      {
        id: "home-line-smart",
        title: text("Smart Home", "المنزل الذكي"),
        copy: text(
          "Device modules, consultations, and install-ready upgrade paths.",
          "أجهزة واستشارات ومسارات ترقية جاهزة للتركيب.",
        ),
        stat: text("Consultation to install", "من الاستشارة إلى التركيب"),
        link: text("Open section", "افتح القسم"),
      },
    ],
    marketSignals: [
      { id: "signal-zones", label: text("Hot zones", "المناطق النشطة"), value: text("Zagazig / New Cairo / Shorouk", "الزقازيق / القاهرة الجديدة / الشروق") },
      { id: "signal-response", label: text("Typical response", "زمن الاستجابة"), value: text("30 minutes", "30 دقيقة") },
      { id: "signal-terms", label: text("Flexible terms", "المرونة"), value: text("Up to 7 years installments", "تقسيط حتى 7 سنوات") },
    ],
    ribbons: [
      item("ribbon-visits", "Site visits", "زيارات الموقع"),
      item("ribbon-installments", "Installments", "تقسيط"),
      item("ribbon-finishing", "Luxury finishing", "تشطيب فاخر"),
      item("ribbon-smart", "Smart-ready living", "جاهز للمنزل الذكي"),
    ],
    dashboardStats: [
      { id: "projects", label: text("Projects", "المشروعات"), hint: text("Flagship developments ready for a scalable catalogue.", "مشروعات رئيسية جاهزة للعرض داخل كتالوج قابل للتوسع.") },
      { id: "open-leads", label: text("Open leads", "الطلبات المفتوحة"), hint: text("Requests currently waiting for admin follow-up.", "طلبات حالية ما زالت في انتظار المتابعة من الإدارة.") },
      { id: "services", label: text("Services", "الخدمات"), hint: text("Real estate, finishing, and smart home.", "العقارات والتشطيب والمنزل الذكي.") },
      { id: "response-sla", label: text("Response SLA", "زمن الاستجابة"), hint: text("Target response time for newly submitted leads.", "المدة المستهدفة للرد على الطلبات الجديدة.") },
    ],
    intentCards: [
      decisionCard(
        "home-intent-projects",
        "Buy or invest",
        "شراء أو استثمار",
        "Explore projects and available units",
        "استكشف المشروعات والوحدات المتاحة",
        "Built for buyers and investors who want a shortlist before booking a visit.",
        "مناسب للمشتري أو المستثمر الذي يريد قائمة مختصرة قبل حجز الزيارة.",
        "Explore Projects",
        "استكشف المشروعات",
      ),
      decisionCard(
        "home-intent-finishing",
        "Finishing",
        "تشطيب",
        "Get a clearer finishing quote",
        "احصل على عرض سعر أوضح للتشطيب",
        "Compare packages first, then request pricing or a first consultation.",
        "قارن الباقات أولًا ثم اطلب عرض السعر أو الاستشارة الأولى.",
        "Get Quote",
        "اطلب عرض سعر",
      ),
      decisionCard(
        "home-intent-smart",
        "Smart Home",
        "منزل ذكي",
        "Match the solution before the setup",
        "حدد الحل قبل التركيب",
        "Start with the use case, then move into the right consultation or installation plan.",
        "ابدأ بحالة الاستخدام ثم انتقل إلى خطة الاستشارة أو التركيب المناسبة.",
        "Request Consultation",
        "اطلب استشارة",
      ),
    ],
    trustItems: [
      valueCard(
        "home-trust-response",
        "Response speed",
        "سرعة الاستجابة",
        "Fast follow-up",
        "متابعة سريعة",
        "Requests are routed to the right team for the selected service.",
        "يصل الطلب مباشرة إلى الفريق المناسب للخدمة المختارة.",
      ),
      valueCard(
        "home-trust-clarity",
        "Decision clarity",
        "وضوح القرار",
        "One next step",
        "خطوة تالية واحدة",
        "Each page is shaped around one primary conversion action.",
        "كل صفحة مصممة حول إجراء تحويل أساسي واحد.",
      ),
      valueCard(
        "home-trust-flow",
        "Structured flow",
        "رحلة منظمة",
        "Visit or quote",
        "زيارة أو عرض سعر",
        "The visitor knows what happens immediately after submission.",
        "الزائر يعرف ما الذي سيحدث مباشرة بعد الإرسال.",
      ),
    ],
    bookingItems: [
      item("home-booking-1", "Pick the right path first: projects, finishing, or smart home.", "حدد المسار المناسب أولًا: مشروعات أو تشطيب أو منزل ذكي."),
      item("home-booking-2", "The clearer the request, the faster the recommendation.", "كلما كان الطلب أوضح، كان الترشيح أسرع."),
      item("home-booking-3", "Submit without commitment, then refine details with the team.", "أرسل الطلب بدون التزام ثم استكمل التفاصيل مع الفريق."),
    ],
  },
  projects: {
    eyebrow: text("Projects", "المشروعات"),
    title: text("Dynamic property catalogue", "كتالوج عقاري ديناميكي"),
    description: text(
      "Projects live in one data model with detail pages, unit inventories, and pricing metadata.",
      "المشروعات موجودة داخل نموذج بيانات واحد مع صفحات تفصيلية ووحدات وبيانات تسعير.",
    ),
    from: text("From", "ابتداءً من"),
    installmentsUpTo: text("Installments up to", "تقسيط حتى"),
    years: text("years", "سنوات"),
    unitsListed: text("units listed", "وحدات متاحة"),
    viewProject: text("View project details", "عرض تفاصيل المشروع"),
    compareTitle: text("Pick the decision type before browsing projects", "اختر نوع القرار قبل استعراض المشروعات"),
    compareLabel: text("Best for", "مناسب لـ"),
    bookVisit: text("Book site visit", "احجز زيارة موقع"),
    visitReasonTitle: text("Why book now instead of browsing only?", "لماذا الحجز الآن أفضل من الاكتفاء بالتصفح؟"),
    curatedInventoryLabel: text("Curated inventory", "المخزون المختار"),
    curatedInventoryNote: text("Signature developments presented as a cleaner high-end catalogue.", "مشروعات مميزة معروضة بشكل أوضح وأفخم لتسريع القرار."),
    locationsLabel: text("Locations", "المواقع"),
    locationsNote: text("Zoned across the strongest real-estate corridors inside the current catalog.", "منتشرة عبر أقوى المحاور العقارية داخل الكتالوج الحالي."),
    installmentStatLabel: text("Installments", "التقسيط"),
    installmentStatNote: text("Years currently available across the published project mix.", "عدد سنوات التقسيط المتاحة حاليًا عبر المشروعات المنشورة."),
    flagshipLabel: text("Flagship release", "المشروع الرئيسي"),
    launchModeLabel: text("Launch mode", "وضع الطرح"),
    featuredMode: text("Featured", "مميز"),
    coreMode: text("Core listing", "إدراج أساسي"),
    compareItems: [
      decisionCard(
        "projects-residence",
        "Residence",
        "سكن",
        "If the goal is living",
        "لو الهدف هو السكن",
        "Start with the right size, location, and visit readiness.",
        "ابدأ بالمساحة المناسبة والموقع والاستعداد للزيارة.",
      ),
      decisionCard(
        "projects-investment",
        "Investment",
        "استثمار",
        "If the goal is investment",
        "لو الهدف هو الاستثمار",
        "Prioritize marketable projects, demand, and easier follow-up.",
        "ركز على المشاريع القابلة للتسويق والطلب وسهولة المتابعة.",
      ),
      decisionCard(
        "projects-admin",
        "Administrative",
        "إداري",
        "If the goal is business use",
        "لو الهدف هو الاستخدام الإداري",
        "Focus on accessibility, frontage, and commercial suitability.",
        "ركز على الوصول والواجهة وطبيعة الاستخدام التجاري أو الإداري.",
      ),
    ],
    visitReasons: [
      item("projects-reason-1", "The right project gets identified faster than open-ended browsing.", "تحديد المشروع المناسب أسرع من المقارنة المفتوحة فقط."),
      item("projects-reason-2", "The team can shortlist units around your budget before the visit.", "يمكن للفريق ترشيح وحدات قريبة من ميزانيتك قبل الزيارة."),
      item("projects-reason-3", "You move into a real next step instead of staying in passive exploration.", "تنتقل إلى خطوة حقيقية بدل البقاء في تصفح سلبي."),
    ],
  },
  book: {
    eyebrow: text("Book", "الحجز"),
    title: text("One booking surface for projects, finishing, and smart home.", "سطح حجز موحد للمشروعات والتشطيب والمنزل الذكي."),
    description: text(
      "This page acts as a shared conversion endpoint while the admin domain manages incoming requests.",
      "هذه الصفحة تعمل كنقطة تحويل موحدة بينما يدير دومين الإدارة الطلبات الواردة.",
    ),
  },
  finishing: {
    eyebrow: text("Finishing", "التشطيب"),
    title: text("Structured pricing and packages instead of generic luxury visuals.", "تسعير وباقات منظمة بدل الاكتفاء بصور فاخرة عامة."),
    description: text(
      "This section is driven by package data, estimation logic, and a direct quote flow.",
      "هذا القسم يعتمد على بيانات الباقات ومنطق التقدير ومسار طلب عرض سعر مباشر.",
    ),
    recommended: text("Recommended", "موصى به"),
    package: text("Package", "باقة"),
    beforeAfterAlt: text("Before and after finishing concept", "مفهوم قبل وبعد التشطيب"),
    whyTitle: text("Why Veyra for finishing?", "لماذا Veyra للتشطيب؟"),
    processTitle: text("How does the journey work?", "كيف تسير الرحلة؟"),
    faqTitle: text("Frequently asked questions", "أسئلة متكررة"),
    stickyPrimary: text("Get quote", "اطلب عرض سعر"),
    stickySecondary: text("View calculator", "اعرض الحاسبة"),
    whyCards: [
      valueCard("finishing-why-1", "Pricing clarity", "وضوح التسعير", "Clear price per meter", "سعر متر واضح", "Packages provide a clearer benchmark before the visit.", "الباقات تعطي نقطة بداية أوضح قبل الزيارة."),
      valueCard("finishing-why-2", "Faster decision", "قرار أسرع", "Direct comparison", "مقارنة مباشرة", "Clients compare tiers before speaking to the team.", "العميل يقارن المستويات قبل التحدث مع الفريق."),
      valueCard("finishing-why-3", "Next step clarity", "وضوح الخطوة التالية", "Quote request", "طلب عرض سعر", "The visitor knows what happens immediately after submitting.", "الزائر يعرف ما الذي يحدث مباشرة بعد الإرسال."),
    ],
    processSteps: [
      item("finishing-step-1", "Choose the package closest to your budget and finishing level.", "اختر الباقة الأقرب إلى ميزانيتك ومستوى التشطيب المطلوب."),
      item("finishing-step-2", "The team reviews the area and type of finishing required.", "يراجع الفريق المساحة ونوع التشطيب المطلوب."),
      item("finishing-step-3", "You receive an initial quote, then a visit or follow-up is arranged.", "يصل إليك عرض مبدئي ثم يتم ترتيب الزيارة أو المتابعة."),
    ],
    faqs: [
      faq("finishing-faq-1", "Is the displayed price final?", "هل السعر المعروض نهائي؟", "The listed rate is an initial benchmark, then the team confirms details after review or inspection.", "السعر المعروض نقطة بداية تقريبية ثم يؤكد الفريق التفاصيل بعد المراجعة أو المعاينة."),
      faq("finishing-faq-2", "Can I request only part of the finishing scope?", "هل أستطيع طلب جزء من نطاق الأعمال فقط؟", "Yes. The team can guide the scope based on the exact finishing work you need.", "نعم، يمكن للفريق توجيه النطاق حسب الأعمال التي تحتاجها بالضبط."),
      faq("finishing-faq-3", "What happens after I submit?", "ماذا يحدث بعد الإرسال؟", "The team confirms the requirement, then prepares the quote or schedules the next step.", "يؤكد الفريق الاحتياج ثم يجهز عرض السعر أو ينسق الخطوة التالية."),
    ],
  },
  smartHome: {
    eyebrow: text("Smart Home", "المنزل الذكي"),
    title: text("A modular smart living flow with devices, packages, and setup requests.", "رحلة معيشة ذكية مرنة تضم الأجهزة والباقات وطلبات التركيب."),
    description: text(
      "The smart-home experience is no longer a one-screen promo. It now has reusable device data and a dedicated installation funnel.",
      "تجربة المنزل الذكي لم تعد شاشة دعائية واحدة، بل أصبحت تعتمد على بيانات أجهزة وباقات قابلة لإعادة الاستخدام.",
    ),
    howItWorks: text("How it works", "كيف تعمل الخدمة"),
    steps: [
      item("smart-step-1", "Consultation", "استشارة"),
      item("smart-step-2", "Device selection", "اختيار الأجهزة"),
      item("smart-step-3", "Installation", "التركيب"),
      item("smart-step-4", "Mobile setup", "إعداد التطبيق"),
    ],
    whyTitle: text("Why start with a smart-home consultation?", "لماذا تبدأ باستشارة منزل ذكي؟"),
    useCaseTitle: text("Most common use cases", "الحالات الأكثر شيوعًا"),
    faqTitle: text("Frequently asked questions", "أسئلة متكررة"),
    stickyPrimary: text("Request consultation", "اطلب استشارة"),
    stickySecondary: text("Use cases", "حالات الاستخدام"),
    whyCards: [
      valueCard("smart-why-1", "Solution before device", "الحل قبل الجهاز", "Define the need", "حدد الاحتياج", "The goal is not buying hardware first, but choosing the right automation scenario.", "الهدف ليس شراء جهاز أولًا بل اختيار السيناريو الأنسب."),
      valueCard("smart-why-2", "Cleaner setup", "تركيب أنظف", "Clearer plan", "خطة أوضح", "The team maps the installation path before execution.", "الفريق يحدد مسار التركيب قبل التنفيذ."),
      valueCard("smart-why-3", "Faster decision", "قرار أسرع", "Better package fit", "باقة أنسب", "The visitor moves from scattered options into one clearer recommendation.", "ينتقل الزائر من التشتت إلى توصية أوضح وأسرع."),
    ],
    useCases: [
      item("smart-case-1", "Security and monitoring around entrances and key zones.", "أمان ومراقبة للمداخل والنقاط الحساسة."),
      item("smart-case-2", "Better control of lighting, curtains, or access.", "تحكم أسهل في الإضاءة أو الستائر أو الأقفال."),
      item("smart-case-3", "A gradual smart-home rollout without overcomplication.", "تجهيز تدريجي للمنزل الذكي بدون تعقيد كبير."),
    ],
    faqs: [
      faq("smart-faq-1", "Do I need to replace everything at home?", "هل أحتاج لتغيير كل شيء في المنزل؟", "No. You can start with one use case first, then expand gradually.", "لا، يمكنك البدء بحالة استخدام واحدة ثم التوسع تدريجيًا."),
      faq("smart-faq-2", "Will the devices work from my phone?", "هل تعمل الأجهزة من الهاتف؟", "Yes. The consultation helps define the best control experience and setup path.", "نعم، والاستشارة تساعد على تحديد تجربة التحكم ومسار الإعداد الأنسب."),
      faq("smart-faq-3", "What happens after I submit?", "ماذا يحدث بعد الإرسال؟", "The team reviews the scenario you need, then recommends the right package or device mix.", "يراجع الفريق السيناريو المطلوب ثم يرشح الباقة أو مزيج الأجهزة المناسب."),
    ],
  },
  projectDetail: {
    projectHighlights: text("Project highlights", "مميزات المشروع"),
    bookVisit: text("Book a site visit", "احجز زيارة للموقع"),
    availableUnits: text("Available units", "الوحدات المتاحة"),
    residentialLabel: text("Residential", "سكني"),
    administrativeLabel: text("Administrative", "إداري"),
    penthouseLabel: text("Penthouse", "بنتهاوس"),
    floor: text("Floor", "الدور"),
    bedrooms: text("bedrooms", "غرف نوم"),
    officeReady: text("Office ready", "مناسب للإدارة"),
    requestVisit: text("Request a visit", "اطلب زيارة"),
    requestDescription: text(
      "Leads submitted here can be pushed straight into the admin pipeline and tied to a real project journey.",
      "الطلبات المرسلة من هنا يمكن أن تدخل مباشرة إلى الـ CRM وترتبط برحلة مشروع حقيقية.",
    ),
    upTo: text("Up to", "حتى"),
    years: text("years", "سنوات"),
    sqm: text("sqm", "متر"),
    available: text("Available", "متاح"),
    reserved: text("Reserved", "محجوز"),
    perSqm: text("/ sqm", "/ متر"),
    visitNow: text("Book a visit now", "احجز معاينة الآن"),
    viewInventory: text("View inventory", "عرض الوحدات"),
    whyTitle: text("Why this project?", "لماذا هذا المشروع؟"),
    whyDescription: text(
      "A short decision layer that helps the buyer move faster before contacting sales or booking a visit.",
      "طبقة قرار سريعة تساعد العميل على التحرك أسرع قبل التواصل أو الحجز.",
    ),
    fitTitle: text("Who is this project for?", "هذا المشروع مناسب لمن؟"),
    processTitle: text("What happens after booking?", "ماذا يحدث بعد الحجز؟"),
    faqTitle: text("Frequently asked questions", "أسئلة متكررة"),
    responseTitle: text("Response speed", "سرعة الاستجابة"),
    responseText: text(
      "This page is structured to route you directly to the team responsible for the project.",
      "هذه الصفحة مصممة لتوصلك مباشرة إلى الفريق المسؤول عن المشروع.",
    ),
    urgencyTitle: text("Before you decide", "مهم قبل القرار"),
    urgencyText: text(
      "The clearer the request now, the faster the team can match you with the right unit and visit time.",
      "كلما كان الطلب أوضح الآن كان ترشيح الوحدة وموعد الزيارة أسرع.",
    ),
    stickyPrimary: text("Book visit", "احجز زيارة"),
    stickySecondary: text("Units", "الوحدات"),
    whyCards: [
      valueCard("project-why-1", "Starting from", "يبدأ من", "Pricing anchor", "نقطة سعر", "Show a clear starting point before the visit.", "اعرض نقطة سعر واضحة قبل الزيارة."),
      valueCard("project-why-2", "Installments", "التقسيط", "Flexible term", "مدة مرنة", "Help the buyer estimate commitment before speaking to sales.", "ساعد العميل على فهم الالتزام قبل التواصل مع المبيعات."),
      valueCard("project-why-3", "Availability", "التوفر", "Live inventory", "وحدات حية", "Use available inventory to encourage faster action.", "استخدم الوحدات المتاحة لدفع العميل إلى التحرك أسرع."),
    ],
    fitItems: [
      item("project-fit-1", "A buyer who wants a strong address and a clear next step.", "مشتري يريد عنوانًا قويًا وخطوة تالية واضحة."),
      item("project-fit-2", "An investor looking for a marketable, premium-ready project.", "مستثمر يبحث عن مشروع قابل للتسويق وجاهز للاستثمار."),
      item("project-fit-3", "A client who wants quick comparison before visiting.", "عميل يريد مقارنة سريعة قبل النزول للزيارة."),
    ],
    processSteps: [
      item("project-step-1", "Our sales team reviews the request and contacts you quickly.", "يراجع فريق المبيعات الطلب ويتواصل معك سريعًا."),
      item("project-step-2", "A visit or consultation slot is arranged around your availability.", "يتم ترتيب موعد الزيارة أو الاستشارة حسب وقتك."),
      item("project-step-3", "You receive unit recommendations matched to your size and budget.", "تصلك ترشيحات وحدات مناسبة للمساحة والميزانية."),
    ],
    faqs: [
      faq("project-faq-1", "Is the visit free?", "هل الزيارة مجانية؟", "Yes. The first visit request is commitment-free.", "نعم، طلب الزيارة الأولى بدون التزام."),
      faq("project-faq-2", "Can I know the best unit before visiting?", "هل أستطيع معرفة أنسب وحدة قبل الزيارة؟", "Yes. The team can shortlist options based on budget and preferred size.", "نعم، يمكن للفريق ترشيح وحدات حسب الميزانية والمساحة المفضلة."),
      faq("project-faq-3", "Do displayed prices help with the decision?", "هل الأسعار المعروضة تساعد في القرار؟", "Yes. They provide a clear starting point before the detailed follow-up with sales.", "نعم، فهي تعطيك نقطة بداية واضحة قبل المتابعة التفصيلية مع المبيعات."),
    ],
  },
};
